# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21cf6c9895dc36cbc477c5989bba47952d56f7dd8bb126ec6962ffe8ee07d4d27ae4638aec578304540fb3330d43bd52d6cd48a7c32b0aa3e797783d90b3b527

test:
  secret_key_base: f7bc10f1a4db128b25b65280e6fe0c0145f5056b8f3c38246607a6d2582daafde51ecebb6aae2e7721c2fc0d93d336f02978978f40c209981df6a49c3b417f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
